### ISSUE TITLE
The `enumeration.has` function can return `False` when given a valid enumeration identifier.

### ISSUE THREAD

**Issue by arizvisa** [arizvisa/ida-minsc#139]
The following was reported in issue #137 while the original reporter was troubleshooting the issue. The `enumeration.by_identifier` function uses the `enumeration.has` implementation to determine whether the given identifier has an enumeration mapped to it. The implementation perfmrs this check by verifying that the provided identifier is a valid id for the database type (masked with 0xFF000000 for 32-bit, and 0xFF00000000000000 for 64-bit) and then checking if the relevant enumeration "altvals" are defined for it. This low-level way of checking if something is an enumeration was done because on earlier versions of IDA, IDA would consider some "custom data" or "structure" identifiers as enumerations which is wrong.

---
hm, this seems to have to do with netnode, too, since it uses `has`:

~~~
Python>enum.by_identifier(0xff00020f)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\users\c0d3\Application Data\Hex-Rays\IDA Pro\ida_minsc\base\enumeration.py", line 114, in by_identifier
    raise E.EnumerationNotFoundError(u"{:s}.by_identifier({!s}) : Unable to locate the enumeration with the specified identifier ({:#x}).".format(__name__, eid, eid))
internal.exceptions.EnumerationNotFoundError: enumeration.by_identifier(4278190607) : Unable to locate the enumeration with the specified identifier (0xff00020f).
Python>idaapi.get_enum_name(0xff00020f)
'RAM1_01'
~~~

_Originally posted by @c0d3z3r0 in https://github.com/arizvisa/ida-minsc/issues/137#issuecomment-877783107_

**Comment by arizvisa** [comment]
Ftr, this issue was reported in IDA v7.5.201028 using a 32-bit database.

**Comment by arizvisa** [comment]
@c0d3z3r0, for that enumeration id (0xff00020f for "RAM1_01") can you copy and paste its contents from the enumeration tab, and also can you give me the output for the following:
```
import internal
print(internal.netnode.alt.repr(0xFF00020F))
```

It should look something like this on a 32-bit database:
```
print(internal.netnode.alt.repr(enum.by('ASN1encodingrule_e')))
fffffff8 : 0x124 (292)
fffffffb : 0x42 (66)
fffffffd : 0x1100000 (17825792)
ffffffff : 0x7 (7)
```

**Comment by c0d3z3r0** [comment]
RAM1_01 enum:

~~~
00000003 ; For bitfields the line prefixes display the bitmask
00000003 ; ---------------------------------------------------------------------------
00000003
00000003 ; enum RAM1_01, bitfield, width 1 byte
00000003 SLED_S12345      .equ 11b      (mask)
00000003 SLED_S45:        .equ 1
00000003 SLED_S123:       .equ 10b
0000000C SLED_STATE       .equ 1100b      (mask)
0000000C SLED_WAKING:     .equ 100b
0000000C SLED_RUNNING:    .equ 1000b
0000000C
~~~

... and the requested output:

~~~
Python>import internal
Python>idaapi.get_enum("RAM1_01")
0xff00020f
Python>print(internal.netnode.alt.repr(0xFF00020F))
fffffffb : 0x9 (9)
fffffffd : 0x6600000 (106954752)
ffffffff : 0x4 (4)
~~~

**Comment by arizvisa** [comment]
Okay, it looks like one of the enumeration "altvals" that I'm testing for (ENUM_ORDINAL) doesn't exist. I'm probably testing for these too hard anyways and should relax them a bit. As a temporary fix, you can edit "base/enumeration.py" and near the top where the defintion for the `has` function exists which looks like:

```
def has(enum):
    '''Return truth if the enumeration `enum` exists within the database.'''
    ENUM_QTY_IDX, ENUM_FLG_IDX, ENUM_FLAGS, ENUM_ORDINAL = -1, -3, -5, -8
    alts = {idaapi.BADADDR & uval for uval in [ENUM_FLG_IDX, ENUM_FLAGS, ENUM_ORDINAL]}
    return interface.node.is_identifier(enum) and all(internal.netnode.alt.has(enum, idx) for idx in alts)
```

You can then just remove the test for `ENUM_ORDINAL" so that it looks like:
```
def has(enum):
    '''Return truth if the enumeration `enum` exists within the database.'''
    ENUM_QTY_IDX, ENUM_FLG_IDX, ENUM_FLAGS, ENUM_ORDINAL = -1, -3, -5, -8
    alts = {idaapi.BADADDR & uval for uval in [ENUM_FLG_IDX, ENUM_FLAGS]}
    return interface.node.is_identifier(enum) and all(internal.netnode.alt.has(enum, idx) for idx in alts)
```

This probably isn't the greatest remedy, but it should work for now. I'll properly research it and write a PR to fix it tomorrows as it's already pretty late in my current timezone.

**Comment by c0d3z3r0** [comment]
> You can then just remove the test for `ENUM_ORDINAL" so that it looks like:

Nice, this did the trick!

Thanks for your great work :-)

**Comment by arizvisa** [comment]
Okay. I have a PR written that I might merge, but can you check one more thing for that enumeration id?

Can you print the output of `idaapi.get_enum_idx(0xff00020f)`? I think that "ENUM_ORDINAL" altval is supposed to be the enumeration index, so it's weird that it isn't defined. It might be the first enumeration and hence have an ordinal of `0`, but I want to be sure before I merge the PR.

**Comment by c0d3z3r0** [comment]
> Okay. I have a PR written that I might merge (#140), but can you check one more thing for that enumeration id?
> 
> Can you print the output of `idaapi.get_enum_idx(0xff00020f)`? I think that "ENUM_ORDINAL" altval is supposed to be the enumeration index, so it's weird that it isn't defined. It might be the first enumeration and hence have an ordinal of `0`, but I want to be sure before I merge the PR.

That seems right. It's 0 for the first enum and 1 for the second

**Comment by arizvisa** [comment]
Okay, Awesome. Thanks.

**Comment by arizvisa** [comment]
PR #140 was just merged which hopefully fixes this issue. Closing it as a result. If the issue is still there for some reason, let me know and I can re-open.

You should be able to do a `git pull` which should sync your copy of the repo to the most recent "master" branch. This should include the fixes from the 2 issues you reported.
