### ISSUE TITLE
Suggestion: Add the name DLL as that is what IDA calls the shared objects

### ISSUE THREAD

**Issue by Harding-Stardust** [arizvisa/ida-minsc#167]
As a windows RE I am missing the name "is_dll()" as that is what IDA calls shared objects: 
```
ida_idaapi.get_inf_structure().is_dll()
```
https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/base/database.py#L187

**Comment by arizvisa** [comment]
I can totally add that alias for you. It makes sense. (Ftr, I'm a windows RE also).

**Comment by arizvisa** [comment]
This was closed by PR #186.
