### ISSUE TITLE
Minor doc change: says "all" but only 1 is returned

### ISSUE THREAD

**Issue by Harding-Stardust** [arizvisa/ida-minsc#170]
Here:
https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/base/database.py#L462C20-L462C20

and here:
https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/base/database.py#L467

**Comment by arizvisa** [comment]
Closing as requested.
