### ISSUE TITLE
Wrong path on windows

### ISSUE THREAD

**Issue by Harding-Stardust** [arizvisa/ida-minsc#172]
The correct path is:
%APPDATA%\Hex-Rays\IDA Pro
Note the missing "roaming", this is included in %APPDATA%

https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/README.md?plain=1#L39

**Comment by arizvisa** [comment]
Both issue #172 and #173 will be combined in a future PR since they reside within the same file.

**Comment by arizvisa** [comment]
This was closed by PR #190. If you feel this does not resolve your issue, please let me know and I can re-open.
