### ISSUE TITLE
Using double quotation marks makes this work on Windows also

### ISSUE THREAD

**Issue by Harding-Stardust** [arizvisa/ida-minsc#173]
```
pip install -r "requirements.txt"
```
https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/README.md?plain=1#L58

**Comment by arizvisa** [comment]
Both issue #172 and #173 will be combined in a future PR since they reside within the same file.

**Comment by arizvisa** [comment]
This was closed by PR #190. If you feel this does not resolve your issue, please let me know and I can re-open.
