### ISSUE TITLE
The instruction namespace should return a ida_ua.insn_t() object instead of a string

### ISSUE THREAD

**Issue by Harding-Stardust** [arizvisa/ida-minsc#174]
There is database.disassemble() for the string, use the database.instruction() to get the ida_ua.insn_t instead

https://github.com/arizvisa/ida-minsc/blob/af07f167a0992aed3f3a2a1670593880baa57820/base/database.py#L793C21

**Comment by Harding-Stardust** [comment]
You are correct, I misstook the database.instruction for the instruction module. You can close this (I would still prefer if the database.instruction was the instruction module like how the database.function is the function.py module)

**Comment by arizvisa** [comment]
Closing as per request.
