### ISSUE TITLE
How check current code of function ? 

### ISSUE THREAD

**Issue by gool123456** [arizvisa/ida-minsc#52]
Hi ! arizvisa , 
How to judge whether the current code is a function?
Using db.functions.xxx() will fail, because I have a section of Code that is not defined as a function, it is Red, when it has not been defined as a function,
Is there a corresponding method to detect whether it is a function? I use db.type.has_name(xx), but the result is not ideal.
Is there such a function type.is_func()?

**Comment by arizvisa** [comment]
You can use `func.within(ea)` (just `func.within()` for current address).

Or I think you can use `func.contains(function_ea, ea)` where both parameters are the address you want to check..The semantics are read in your head like "Is `ea` in the function at `function_ea`."

**Comment by arizvisa** [comment]
Maybe a better way to think about it is the `database.functions` namespace is actually for searching IDA's function list, similar to `database.exports`, and `database.imports`, etc. Then anything in `database.*` is for things specific to an address. Everything in `function` (or `func`) is then used for figuring out information related to your code being an actual function or not.

The `segment` (or `seg`) module has the same semantics for `segment.contains` and `segment.within` (although `segment.within` will always return true unless you give it an invalid address iirc).

**Comment by gool123456** [comment]
Thank you for solving my question perfectly !!!

**Comment by arizvisa** [comment]
Awesome. hth. Can you close this issue since it's been answered?

**Comment by gool123456** [comment]
@arizvisa ok, but i can't close it
