### ISSUE TITLE
GH-57 make comment has some error repost. 

### ISSUE THREAD

**Issue by gool123456** [arizvisa/ida-minsc#59]
hi, use db.comment function :

Python>db.comment(0x89d117, "123")

CRITICAL:root:internal.interface.priorityhook.callback(9031959, False) : Callback for "IDB_Hooks.cmt_changed" with priority (+0) raised an exception while executing <bound method type.old_changed of <class 'hooks.address'>>
WARNING:root:internal.interface.priorityhook.callback(9031959, False) : Traceback ("IDB_Hooks.cmt_changed" was hooked at)
WARNING:root:internal.interface.priorityhook.callback(9031959, False) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 1059, in ida_is_busy_sucking_cocks
WARNING:root:internal.interface.priorityhook.callback(9031959, False) :     make_ida_not_suck_cocks(idaapi.NW_INITIDA)
WARNING:root:internal.interface.priorityhook.callback(9031959, False) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 993, in make_ida_not_suck_cocks
WARNING:root:internal.interface.priorityhook.callback(9031959, False) :     ui.hook.idb.add('cmt_changed', address.old_changed, 0)
WARNING:root:internal.interface.priorityhook.callback(9031959, False) : 
WARNING:root:internal.interface.priorityhook.callback(9031959, False) : Traceback (most recent call last):
WARNING:root:internal.interface.priorityhook.callback(9031959, False) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\base\_interface.py", line 373, in closure
WARNING:root:internal.interface.priorityhook.callback(9031959, False) :     result = callable(*parameters)
WARNING:root:internal.interface.priorityhook.callback(9031959, False) :   File "C:\Users\Hskyre\AppData\Roaming\Hex-Rays\IDA Pro\misc\hooks.py", line 213, in old_changed
WARNING:root:internal.interface.priorityhook.callback(9031959, False) :     logging.debug(u"{:s}.old_changed({:#x}, {:d}) : Received comment.changed event for a {:s} comment at {:#x}.".format('.'.join((__name__, cls.__name__)), ea, repeatable, 'repeatable' if repeatable else 'non-repeatable', ea))
WARNING:root:internal.interface.priorityhook.callback(9031959, False) : NameError: global name 'repeatable' is not defined
WARNING:root:internal.interface.priorityhook.callback(9031959, False) : 
123

**Comment by gool123456** [comment]
using ida 6.8

**Comment by arizvisa** [comment]
Can you see if PR #60 fixes it?

**Comment by arizvisa** [comment]
Closing this issue as it was fixed by PR #60. Fixing this issue manifested a different issue when trying to update the comment cache. That new issue was created in #61.

**Comment by arizvisa** [comment]
Hi, @gool123456. Sorry to message you on this closed issue, but I was wondering if you're around, reversing, and still using this plugin (and if you're still using it on older versions of IDA with Python2).

I'm finally adding support for Python3 in PR #84, but I still want to make sure that things are still compatible with older versions of IDA and still with Python2. If you're still using it, do you mind checking out that PR and using it to see if you encounter any issues? To test it out you'd do `git fetch origin refs/pull/84/head:testing`, and then `git checkout testing`.

If you're not, that's okay.

**Comment by gool123456** [comment]
@arizvisa Hi , Ali Rizvi,  At present, I am using ida-minsc of ida6.8 and 7.2. It is relatively smooth. I have not used too many new methods. I have not found other problems. I will give you feedback in time if there are problems, thank you for your continuous update.: )

**Comment by arizvisa** [comment]
Awesome. I've been slowly working on adding this Python3 support, and it's been a lot of work. But I definitely want to make sure that it doesn't end up breaking anything on older versions of IDA (and also Python2). Thank you soo much, @gool123456. I appreciate your help with reporting problems!
